### ISSUE TITLE
FILE_DS datastore not working

### ISSUE THREAD

**Issue by ulide4** [LINBIT/addon-linstor#3]
Hi again,

FILE_DS functionality is not working. I am using the latest release (0.9.3) of the addon. The documentation states states it should work... "Linstor driver can also be used as a system/**context** datastore," but the example is only for a SYSTEM_DS.

Steps to reproduce:
1. Create linstor image datastore and system datastore according documentation. VM instantiation (tty linux from ONE Marketplace) works fine.
2. Create linstor file_ds datastore from the following template:
NAME="hci-file_ds_linstor_a2"
DS_MAD="linstor"
TYPE="FILE_DS"
TM_MAD="linstor"
LINSTOR_AUTO_PLACE="2"
LINSTOR_STORAGE_POOL="filauto2copy"
BRIDGE_LIST= "srv362 srv363 srv364"
3. Upload a testfile to this file_ds datastore works fine
4. Adding the test file to the VM Template (Context -> Files) and instantiate produces following error in oned.log

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 Command execution failed (exit code: 1): /var/lib/one/remotes/tm/linstor/context /var/lib/one/vms/2/context.sh OpenNebula-Image-0:'test' srv364:/var/lib/one//datastores/104/2/disk.2 2 104

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 Traceback (most recent call last):

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 File "/var/lib/one/remotes/tm/linstor/context", line 137, in <module>

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 main()

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 File "/var/lib/one/remotes/tm/linstor/context", line 71, in main

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 shutil.copy2(file, os.path.join(iso_dir, os.path.basename(file)))

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 File "/usr/lib/python2.7/shutil.py", line 144, in copy2

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 copyfile(src, dst)

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 File "/usr/lib/python2.7/shutil.py", line 96, in copyfile

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 with open(src, 'rb') as fsrc:

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 IOError: [Errno 2] No such file or directory: 'OpenNebula-Image-0:test'

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: LOG I 2 Failed to execute transfer manager driver operation: tm_context.

Sun Feb  3 13:15:43 2019 [Z0][VMM][D]: Message received: DEPLOY FAILURE 2 -

Sun Feb  3 13:15:54 2019 [Z0][InM][D]: Monitoring datastore default (1)

Best Regards
Uli

**Comment by rp-** [comment]
This is a misunderstanding, the FILE_DS isn't described on how to create, nor is it in any way tested as you noticed.

**Comment by ulide4** [comment]
Yes, I thought, as it is not 100% clear, to give it a shot and report back. 
When it is ready I can test again...

**Comment by ulide4** [comment]
Hi, 
just wanted to kindly ask, if implementing FILE_DS is on your roadmap? Because this is hindering us to use linstor for our production OpenNebula environment. 
Thanks

**Comment by Philipp-Reisner** [comment]
Very bluntly put: Make LINBIT want to do this feature. I.e. become a LINBIT customer

**Comment by ulide4** [comment]
Fair enough, will come back to you then through business channels.
